# Generated by Django 3.1.6 on 2021-02-18 07:59

from django.db import migrations, models
import django.db.models.deletion
import pdf_render.app.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_dt', models.DateTimeField(auto_now_add=True)),
                ('rendered_dt', models.DateTimeField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PROCESSING'), (2, 'DONE'), (3, 'FAILED')], default=pdf_render.app.enums.DocumentStatus['PROCESSING'])),
                ('n_pages', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_dt', models.DateTimeField(auto_now_add=True)),
                ('page_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.document')),
            ],
        ),
    ]
