name: Test

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: pass
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poppler
        run: sudo apt-get install -y poppler-utils

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(python3 -m pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os}}-pip-

      - name: Install requirements
        run: |
          python3 -m pip install -r requirements/test.txt

      - name: Test with pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_USER: user
          POSTGRES_DB: pdf_render
          POSTGRES_PASSWORD: pass
        run: |
          python3 -m pytest
